### ISSUE TITLE
Recommended settings for Arima HiChIP kit

### ISSUE THREAD

**Issue by jmbeesley** [ChenfuShi/HiChIP_peaks#16]
Hi

Thanks for the method. 
I was hoping you could please expand on section 2.2 from the paper, where it's mentioned that "_our method can be easily tuned by changing the previous parameters_". Are there recommended settings for peak calling for libraries generated with the Arima HiChIP kit?

Thanks
Jonathan

**Comment by ChenfuShi** [comment]
Hi Jonathan,
So first of all you should check that your libraries have properly enriched for H3K27ac regions. You can do this by looking at a non-normalized map and looking for stripes of interactions rather than whole maps.

By looking at the size of the restriction fragments I would suggest trying 5 fragments instead of 3 (default), but you should try both and see how much difference it makes. For sure you cannot use 1 like hichipper because you don't have any self circles and very few re-ligation fragments but even 3 should be plenty. You can look at how many reads have been used if you use 3 vs 5 and see if there's a major difference.

Let me know what you find in your data as we had some problems getting the arima kit working but I think now they have updated their protocol specifically for the arima HiChIP but we haven't tested that.
