### ISSUE TITLE
 the differential peaks were not consistent with the bedgraph signal

### ISSUE THREAD

**Issue by baishengjun** [ChenfuShi/HiChIP_peaks#22]
Hi, 
I run differential peak analysis as you recommend, but the generated differential peaks were not consistent with the bedgraph file visualized in IGV. The treatment bedgraph signal were globally higher than the control in IGV visualized and  does not have down regulate peaks.  However, there ware 3000+ down regulated peaks identified in DEseq2 result.
and the bedgraph file were normalized using the `https://github.com/porchard/normalize_bedgraph` script.
 Can you advise on how to solve this problem?

Thanks a lot,
Bai

**Comment by ChenfuShi** [comment]
Normalising bedgraphs is not a good idea, there are many issues with it because the signal is never consistently enriched across samples (one sample might have more specific ChIP than another). I would trust more what DEseq2 produced, and maybe validate biologically if the peaks make sense (try some pathway analysis?)
